-- [ SELECT_BASIC ]

-- 1. 춘 기술대학교의 학과 이름과 계열을 조회
--   (단, 출력헤더는 "학과 명", "계열" )

SELECT DEPARTMENT_NAME "학과 명", CATEGORY "계열"
FROM TB_DEPARTMENT;

-- 2. 학과의 학과 정원을 출력
SELECT DEPARTMENT_NAME || '의 정원은' "학과 별 정원", CAPACITY || '명 입니다.' " "  
FROM TB_DEPARTMENT;

-- 3. "국어국문학과"에 다니는 여학생 중 현재 휴학중인 여학생을 조회
SELECT STUDENT_NAME 
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
AND SUBSTR(STUDENT_SSN, 8, 1) ='2'  
AND ABSENCE_YN = 'Y';

-- 4. 도서관에서 대출 도서 장기 연체자 조회
SELECT DISTINCT STUDENT_NAME 
FROM TB_STUDENT 
WHERE STUDENT_NO IN ('A513079', 'A513090','A513091', 'A513110', 'A513119');

-- 5. 입학정원이 20명 이상 30명 이하인 학과들의 학과 이름과 계열 출력
SELECT DEPARTMENT_NAME, CATEGORY 
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

-- ** 6. 춘 기술대학교는 총장을 제외하고 모든 교수들이 소속학과가 있다.
-- 	  춘 기술대학교의 총장 이름을 알아내라

SELECT PROFESSOR_NAME 총장이름
FROM TB_PROFESSOR 
LEFT JOIN TB_CLASS_PROFESSOR USING(PROFESSOR_NO)
LEFT JOIN TB_CLASS USING(CLASS_NO);

-- 7. 혹시 전산상 착오로 학과가 지정되어있지 않는 학생이 있는지 확인
SELECT STUDENT_NAME 
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME IS NULL;

-- 8. 수강신청 시 선수과목 여부 확인이 필요
--	 선수과목이 존재하는 과목은 어떤 과목인지 과목번호를 조회
SELECT CLASS_NO 
FROM TB_CLASS 
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9. 춘 대학에는 어떤 계열이 있는지 조회
SELECT DISTINCT CATEGORY 
FROM TB_DEPARTMENT;



-------------------------------------------------------------------------

-- [ SELECT_함수]

-- 1.

SELECT STUDENT_NO 학번, STUDENT_NAME 이름, TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') 입학년도
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '영어영문학과'
ORDER BY ENTRANCE_DATE;

-- 2. 
SELECT PROFESSOR_NAME, PROFESSOR_SSN 
FROM TB_PROFESSOR 
WHERE PROFESSOR_NAME NOT LIKE '___';


-- **3. 나이구하기
SELECT PROFESSOR_NAME 교수이름, SUBSTR(PROFESSOR_SSN, 1,2)나이
FROM TB_PROFESSOR;

-- 4.
SELECT SUBSTR(PROFESSOR_NAME, 2) 이름
FROM TB_PROFESSOR;

-- 5. 재수생 입학자 (20살 이후 입학)
SELECT STUDENT_NO, STUDENT_NAME 
FROM TB_STUDENT 
WHERE EXTRACT(YEAR FOR ENTRANCE_DATE) - EXTRACT(YEAR FOR STUDENT_SSN) 