-- SYS 관리자 계정 이용
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- 사용자 계정 생성
CREATE USER sh IDENTIFIED BY sh1234;

-- 생성한 사용자 계정에 권한을 부여
GRANT CONNECT, RESOURCE, CREATE VIEW TO sh;


-- 테이블 스페이스 할당
ALTER USER sh DEFAULT 
TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;


---------------------------------------------------------------------------
-- sh계정
CREATE TABLE MENU(
	MENU_NO NUMBER PRIMARY KEY,
	MENU_NM VARCHAR2(30) NOT NULL,
	MENU_PRICE NUMBER NOT NULL,
	INVENTORY_QUANTITY NUMBER NOT NULL,
	DELIVERY_DATE DATE DEFAULT SYSDATE
);

ALTER TABLE MENU MODIFY INVENTORY_QUANTITY DEFAULT 0;

COMMENT ON COLUMN MENU.MENU_NO IS '메뉴 번호';
COMMENT ON COLUMN MENU.MENU_NM IS '메뉴명';
--COMMENT ON COLUMN PRODUCT.PRODUCT_ITEM IS '품목';
COMMENT ON COLUMN MENU.MENU_PRICE IS '메뉴 가격';
COMMENT ON COLUMN MENU.INVENTORY_QUANTITY IS '재고 수량';
COMMENT ON COLUMN MENU.DELIVERY_DATE IS '입고 날짜';

CREATE SEQUENCE SEQ_MENU_NO NOCACHE;

INSERT INTO MENU VALUES(SEQ_MENU_NO.NEXTVAL, '아메리카노', 4500, 10, TO_DATE('2022-09-10'));
INSERT INTO MENU VALUES(SEQ_MENU_NO.NEXTVAL, '카페라떼', 5000, 10, TO_DATE('2022-09-10'));
INSERT INTO MENU VALUES(SEQ_MENU_NO.NEXTVAL, '카페모카', 5500, 10, TO_DATE('2022-09-10'));
INSERT INTO MENU VALUES(SEQ_MENU_NO.NEXTVAL, '카라멜마끼아또', 5500, 20, DEFAULT);

COMMIT;
SELECT * FROM MENU;

